---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: 5g-core-cluster

resources:
  - github.com/halleelyasaf/vse-ocp-bases/base/3-master_2-workers?ref=main
patchesStrategicMerge:
  - ./patches/nmstate-config.yaml
  - ./patches/aci.yaml

patches:
  - target:
      version: v1
      kind: Namespace
    patch: |-
      - op: replace
        path: /metadata/labels/name
        value: '5g-core-cluster'
  - target:
      kind: AgentClusterInstall
    patch: |-
      - op: replace
        path: /spec/clusterDeploymentRef/name
        value: '5g-core-cluster'
      - op: replace
        path: /metadata/name
        value: '5g-core-cluster'
  - target:
      kind: SealedSecret
      name: assisted-deployment-pull-secret
    path: ./patches/pullsecret-sealed-patch.yaml
  - target:
      kind: Secret
      name: bmc-super1
    patch: |-
      - op: replace
        path: /metadata/name
        value: '5g-core-cluster-bmc-super1'
      - op: replace
        path: /data/username
        value: 'YWRtaW4K'
      - op: replace
        path: /data/password
        value: 'cmVkaGF0MTIzCg=='
  - target:
      kind: Secret
      name: bmc-super2
    patch: |-
      - op: replace
        path: /metadata/name
        value: '5g-core-cluster-bmc-super2'
      - op: replace
        path: /data/username
        value: 'YWRtaW4K'
      - op: replace
        path: /data/password
        value: 'cmVkaGF0MTIzCg=='
  - target:
      kind: Secret
      name: bmc-super3
    patch: |-
      - op: replace
        path: /metadata/name
        value: '5g-core-cluster-bmc-super3'
      - op: replace
        path: /data/username
        value: 'YWRtaW4K'
      - op: replace
        path: /data/password
        value: 'cmVkaGF0MTIzCg=='
  - target:
      kind: Secret
      name: bmc-worker1
    patch: |-
      - op: replace
        path: /metadata/name
        value: '5g-core-cluster-bmc-worker1'
      - op: replace
        path: /data/username
        value: 'YWRtaW4K'
      - op: replace
        path: /data/password
        value: 'cmVkaGF0MTIzCg=='
  - target:
      kind: Secret
      name: bmc-worker2
    patch: |-
      - op: replace
        path: /metadata/name
        value: '5g-core-cluster-bmc-worker2'
      - op: replace
        path: /data/username
        value: 'YWRtaW4K'
      - op: replace
        path: /data/password
        value: 'cmVkaGF0MTIzCg=='
  - target:
      kind: ManagedCluster
    patch: |-
      - op: replace
        path: /metadata/name
        value: '5g-core-cluster'
  - target:
      kind: BareMetalHost
      name: super1
    path: ./patches/5g-core-cluster-super1-patch.yaml
  - target:
      kind: BareMetalHost
      name: super2
    path: ./patches/5g-core-cluster-super2-patch.yaml
  - target:
      kind: BareMetalHost
      name: super3
    path: ./patches/5g-core-cluster-super3-patch.yaml
  - target:
      kind: BareMetalHost
      name: worker1
    path: ./patches/5g-core-cluster-worker1-patch.yaml
  - target:
      kind: BareMetalHost
      name: worker2
    path: ./patches/5g-core-cluster-worker2-patch.yaml
  - target:
      kind: ClusterDeployment
    path: ./patches/clusterdeployment-patch.yaml
  - target:
      kind: InfraEnv
    path: ./patches/infraenv-patch.yaml
  - target:
      kind: KlusterletAddonConfig
    path: ./patches/klusterletaddon-patch.yaml
  - target:
      kind: ManagedClusterInfo
    patch: |-
      - op: replace
        path: /metadata/name
        value: '5g-core-cluster'
      - op: replace
        path: /metadata/namespace
        value: '5g-core-cluster'