---
apiVersion: agent-install.openshift.io/v1beta1
kind: NMStateConfig
metadata:
  name: nmstate-super1
  labels:
    cluster-name: 5g-core-cluster-nmstate
spec:
  config:
    interfaces:
      - name: ens10f0
        type: ethernet
        state: up
        ipv4:
          address:
            - ip: 192.168.35.53
              prefix-length: 25
          enabled: true
    dns-resolver:
      config:
        server:
          - 192.168.35.30
    routes:
      config:
        - destination: 0.0.0.0/0
          next-hop-address: 192.168.35.1
          next-hop-interface: ens10f0
  interfaces:
    - name: ens10f0
      macAddress: B4:96:91:B7:2E:68
---
apiVersion: agent-install.openshift.io/v1beta1
kind: NMStateConfig
metadata:
  name: nmstate-super2
  labels:
    cluster-name: 5g-core-cluster-nmstate
spec:
  config:
    interfaces:
      - name: ens10f0
        type: ethernet
        state: up
        ipv4:
          address:
            - ip: 192.168.35.54
              prefix-length: 25
          enabled: true
    dns-resolver:
      config:
        server:
          - 192.168.35.30
    routes:
      config:
        - destination: 0.0.0.0/0
          next-hop-address: 192.168.35.1
          next-hop-interface: ens10f0
  interfaces:
    - name: ens10f0
      macAddress: B4:96:91:B7:2D:18
---
apiVersion: agent-install.openshift.io/v1beta1
kind: NMStateConfig
metadata:
  name: nmstate-super3
  labels:
    cluster-name: 5g-core-cluster-nmstate
spec:
  config:
    interfaces:
      - name: ens10f0
        type: ethernet
        state: up
        ipv4:
          address:
            - ip: 192.168.35.55
              prefix-length: 25
          enabled: true
    dns-resolver:
      config:
        server:
          - 192.168.35.30
    routes:
      config:
        - destination: 0.0.0.0/0
          next-hop-address: 192.168.35.1
          next-hop-interface: ens10f0
  interfaces:
    - name: ens10f0
      macAddress: B4:96:91:B7:2E:5C
---
apiVersion: agent-install.openshift.io/v1beta1
kind: NMStateConfig
metadata:
  name: nmstate-worker1
  labels:
    cluster-name: 5g-core-cluster-nmstate
spec:
  config:
    interfaces:
      - name: ens10f0
        type: ethernet
        state: up
        ipv4:
          address:
            - ip: 192.168.35.56
              prefix-length: 25
          enabled: true
    dns-resolver:
      config:
        server:
          - 192.168.35.30
    routes:
      config:
        - destination: 0.0.0.0/0
          next-hop-address: 192.168.35.1
          next-hop-interface: ens10f0
  interfaces:
    - name: ens10f0
      macAddress: B4:96:91:BE:36:94
---
apiVersion: agent-install.openshift.io/v1beta1
kind: NMStateConfig
metadata:
  name: nmstate-worker2
  labels:
    cluster-name: 5g-core-cluster-nmstate
spec:
  config:
    interfaces:
      - name: ens10f0
        type: ethernet
        state: up
        ipv4:
          address:
            - ip: 192.168.35.57
              prefix-length: 25
          enabled: true
    dns-resolver:
      config:
        server:
          - 192.168.35.30
    routes:
      config:
        - destination: 0.0.0.0/0
          next-hop-address: 192.168.35.1
          next-hop-interface: ens10f0
  interfaces:
    - name: ens10f0
      macAddress: B4:96:91:BE:35:A8

