apiVersion: agent-install.openshift.io/v1beta1
kind: NMStateConfig
metadata:
  name: rna4-nmstate
  namespace: rna4
  labels:
    cluster-name: rna4-nmstate
spec:
  config:
    interfaces:
      - name: ens10f0
        type: ethernet
        state: up
        ipv4:
          address:
            - ip: 192.168.35.50
              prefix-length: 25
          enabled: true
    dns-resolver:
      config:
        server:
          - 192.168.35.30
    routes:
      config:
        - destination: 0.0.0.0/0
          next-hop-address: 192.168.35.1
          next-hop-interface: ens10f0
  interfaces:
    - name: ens10f0
      macAddress: "B4:96:91:B7:2E:38"
