---
- name: Login into the OpenShift cluster
  shell: >
    oc login -u kubeadmin -p pWx2Y-5oQdv-AjM6m-gTy5Q --server=https://api.mc.npss.jnpr.bos2.lab:6443 --insecure-skip-tls-verify=true
  register: result
  retries: 5
  delay: 10
  until: not result.failed

- name: Create SealedSecret
  shell: oc create secret generic assisted-deployment-pull-secret --dry-run=client --from-file=.dockerconfigjson={{ pull_secret_dest }}/pull-secret.txt  --type=kubernetes.io/dockerconfigjson -o yaml | kubeseal --controller-name=sealed-secrets-controller --controller-namespace=sealed-secrets --scope cluster-wide --format json | jq '.spec.encryptedData.".dockerconfigjson"'
  register: pull_secret_encrypted

- debug:
    var: "{{ pull_secret_encrypted }}"

- name: Run 3-node generator
  ansible.builtin.import_tasks: 3-node.yaml
  when: type_of_cluster == 3-node


 