---

- name: Create folder for the template
  file:
    path: "{{ config_file_path }}"
    state: directory

- name: Create all the template
  ansible.builtin.template:
     src: "{{ item }}"
     dest: "{{ config_file_path  }}/"{{ item | basename | regex_replace('\.j2$', '') }}
  with_fileglob:
    - "{{ jinja_path }}/*.j2"