---

- name: Create folder for the template
  file:
    path: "{{ config_file_path }}"
    state: directory

- name: Create all the template
  ansible.builtin.template:
     src: "{{ jinja_path }}/{{ item }}.j2"
     dest: ~/ztp/{{ item | basename | regex_replace('\.j2$', '') }}
  with_items: "{{ config_file }}"


- name: Create bmh template
  ansible.builtin.template:
     src: "{{ jinja_path }}/bmc-creds-secret.yaml.j2"
     dest: "~/ztp/{{ cluster_name }}-{{item.name}}.yaml"
  with_items: "{{ servers }}"