---

- name: Create folder for the template
  file:
    path: "{{ config_file_path }}"
    state: directory

- name: Create all the template
  ansible.builtin.template:
     src: "{{ item }}"
     dest: "{{ config_file_path }}{{ item }}"
  with_fileglob:
    - ../files/*.j2