---

- name: Create folder for the template
  file:
    path: "{{ config_file_path }}"
    state: directory

- name: Create all the template
  ansible.builtin.template:
     src: "{{ item }}.j2"
     dest: "{{ config_file_path }}"
  with_fileglob:
    - "{{ jinja_path }}/*"